# Generated by Django 4.2.18 on 2025-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default='Contact Form Submission', max_length=255),
        ),
    ]
